### ISSUE TITLE
Checklist attendus 23-03-2023

### ISSUE THREAD

**Issue by pom421** [pom421/VotingDapp#15]
- [x] lien GitHub
- [x] lien vers vidéo présentant les fonctionnalités
- [x] lien vers déploiement de la dApp
- [x] code: correction faille, commentaire
- [x] code: dapp appelant les fonctions web3
- [x] code: dapp appelant les events
- [x] code: dapp affichage du compte utlisé et des proposals
- [x] dapp: déploiement sur un serveur vercel
- [x] dapp: affichage conditionnel en fonction du compte connecté
- [x] dapp: front travaillé
- [x] README: installation
- [x] README: paragraphe sur la sécurisation/optimisation (parler de la version sans tally vote avec array, sans tally vote avec mapping, citer le cas où on supprimer certains statut) + gas reporter

**Comment by pom421** [comment]
Déploiement sur Sepolia ok

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/3749428/226472161-d08f4760-9b81-4eb6-a4bb-927acae5d6fb.png">
